name: Deploy to 3-idiots-team

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Organization Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 전체 이력 가져오기

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Mirror push to Personal Repository
        run: |
          git remote add personal https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/3-idiots-team/it-diots-official.git
          git push --mirror personal
