name: Deploy to 3-idiots-team

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}

      - name: Add GitHub to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push to target repository with new author
        run: |
          mkdir -p temp_patch
          mkdir -p target_repo

          git format-patch -1 HEAD -o temp_patch

          git clone ${{ secrets.TARGET_REPOSITORY_URL }} target_repo
          cd target_repo

          git config user.name "${{ secrets.DEPLOY_AUTHOR }}"
          git config user.email "${{ secrets.DEPLOY_AUTHOR_EMAIL }}"

          git am $GITHUB_WORKSPACE/temp_patch/*

          git push origin main
