name: Deploy to 3-idiots-team

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}

      - name: Add GitHub to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push to target repository with new author
        run: |
          # 환경변수 설정
          export GIT_AUTHOR_NAME="${{ secrets.DEPLOY_AUTHOR }}"
          export GIT_AUTHOR_EMAIL="${{ secrets.DEPLOY_AUTHOR_EMAIL }}"
          export GIT_COMMITTER_NAME="${{ secrets.DEPLOY_AUTHOR }}"
          export GIT_COMMITTER_EMAIL="${{ secrets.DEPLOY_AUTHOR_EMAIL }}"

          # 타겟 저장소 클론
          git clone ${{ secrets.TARGET_REPOSITORY_URL }} target_repo
          cd target_repo

          # 소스 브랜치의 변경사항 가져오기
          git --git-dir=$GITHUB_WORKSPACE/.git format-patch -k -1 --stdout | \
          git am -k --committer-date-is-author-date

          # 커밋 재작성
          git filter-branch -f --env-filter '
          export GIT_AUTHOR_NAME="${{ secrets.DEPLOY_AUTHOR }}"
          export GIT_AUTHOR_EMAIL="${{ secrets.DEPLOY_AUTHOR_EMAIL }}"
          export GIT_COMMITTER_NAME="${{ secrets.DEPLOY_AUTHOR }}"
          export GIT_COMMITTER_EMAIL="${{ secrets.DEPLOY_AUTHOR_EMAIL }}"
          ' HEAD~1..HEAD

          git push origin main
