name: Deploy to 3-idiots-team

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to target repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:3-idiots-team/it-diots-official.git
          ssh_private_key: ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}
