name: Mirror Monorepo to Personal Repository

on:
  workflow_dispatch:

# 작업 정의
jobs:
  mirror-to-personal-repo:
    runs-on: ubuntu-latest # 실행 환경

    steps:
      # 1. 소스 코드 체크아웃 (모노레포 전체 가져오기)
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 전체 히스토리를 가져오기 위해 필요

      # 2. pixta-dev/repository-mirroring-action 사용
      - name: Mirror to Personal Repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          # 대상 레포지토리 URL (개인 레포지토리 SSH URL)
          target_repo_url: ${{ secrets.TARGET_REPOSITORY_URL }}

          # SSH 개인 키 (GitHub Secrets에 저장된 값 사용)
          ssh_private_key: ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}
