name: Deploy to 3-idiots-team

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: 소스 저장소 체크아웃
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SSH 키 설치
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}

      - name: GitHub를 신뢰할 수 있는 호스트에 추가
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: 새로운 작성자로 대상 저장소에 푸시
        run: |
          # 환경변수 설정
          export GIT_AUTHOR_NAME="${{ secrets.DEPLOY_AUTHOR }}"
          export GIT_AUTHOR_EMAIL="${{ secrets.DEPLOY_AUTHOR_EMAIL }}"
          export GIT_COMMITTER_NAME="${{ secrets.DEPLOY_AUTHOR }}"
          export GIT_COMMITTER_EMAIL="${{ secrets.DEPLOY_AUTHOR_EMAIL }}"

          # 타겟 저장소 클론
          git clone ${{ secrets.TARGET_REPOSITORY_URL }} target_repo
          cd target_repo

          # 소스 브랜치의 변경사항 가져오기 (커밋 히스토리 유지)
          git --git-dir=$GITHUB_WORKSPACE/.git format-patch -k -1 --stdout | \
          git am -k --committer-date-is-author-date || {
            # patch 실패시 fallback: 직접 파일 복사
            cp -r $GITHUB_WORKSPACE/* .
            git add .
            git commit -m "Sync with source repository"
          }

          # 커밋 재작성
          git filter-branch -f --env-filter '
          export GIT_AUTHOR_NAME="${{ secrets.DEPLOY_AUTHOR }}"
          export GIT_AUTHOR_EMAIL="${{ secrets.DEPLOY_AUTHOR_EMAIL }}"
          export GIT_COMMITTER_NAME="${{ secrets.DEPLOY_AUTHOR }}"
          export GIT_COMMITTER_EMAIL="${{ secrets.DEPLOY_AUTHOR_EMAIL }}"
          ' HEAD~1..HEAD

          git push origin main
