name: Deploy to Production

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Push to Personal Repo
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote add personal https://${{ secrets.GH_PAT_TOKEN }}@github.com/3-idiots-team/it-diots-official
          git push personal main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_TOKEN }}

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.PERSONAL_VERCEL_TOKEN }}
          github-token: ${{ secrets.GH_PAT_TOKEN }}
          vercel-org-id: ${{ secrets.PERSONAL_VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.PERSONAL_VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
