name: Deploy to 3-idiots-team

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: 소스 저장소 체크아웃
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SSH 키 설치
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}

      - name: GitHub를 신뢰할 수 있는 호스트에 추가
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: 새로운 작성자로 대상 저장소에 푸시
        run: |
          # 환경변수 설정
          export GIT_AUTHOR_NAME="${{ secrets.DEPLOY_AUTHOR }}"
          export GIT_AUTHOR_EMAIL="${{ secrets.DEPLOY_AUTHOR_EMAIL }}"
          export GIT_COMMITTER_NAME="${{ secrets.DEPLOY_AUTHOR }}"
          export GIT_COMMITTER_EMAIL="${{ secrets.DEPLOY_AUTHOR_EMAIL }}"

          # 타겟 저장소 클론
          git clone ${{ secrets.TARGET_REPOSITORY_URL }} target_repo
          cd target_repo

          # 소스 저장소의 파일들을 타겟 저장소로 복사 (숨김 파일 포함)
          cp -r $GITHUB_WORKSPACE/.[!.]* $GITHUB_WORKSPACE/* ./ 2>/dev/null || :

          # 변경사항이 있는지 확인하고 커밋
          if git status --porcelain | grep .; then
            git add .
            git commit -m "Sync with source repository"
            
            # 커밋 작성자 정보 재작성
            git filter-branch -f --env-filter '
            export GIT_AUTHOR_NAME="${{ secrets.DEPLOY_AUTHOR }}"
            export GIT_AUTHOR_EMAIL="${{ secrets.DEPLOY_AUTHOR_EMAIL }}"
            export GIT_COMMITTER_NAME="${{ secrets.DEPLOY_AUTHOR }}"
            export GIT_COMMITTER_EMAIL="${{ secrets.DEPLOY_AUTHOR_EMAIL }}"
            ' HEAD~1..HEAD

            git push origin main
          else
            echo "No changes to commit"
          fi
